import type { ReportExportRow } from "@/lib/risk-report";
import { classifyRisk, riskLabel } from "@/lib/risk-report";

interface CompetitionData {
  rows: ReportExportRow[];
  catalogSize: number;
  locale: string;
}

export function generateCompetitionReportHTML(data: CompetitionData): string {
  const { rows, catalogSize, locale } = data;
  const isZh = locale === "zh-CN";

  // Compute statistics
  const aucValues = rows.map((r) => parseFloat(r.aucLabel)).filter((v) => !Number.isNaN(v));
  const avgAuc = aucValues.length > 0 ? (aucValues.reduce((a, b) => a + b, 0) / aucValues.length).toFixed(3) : "n/a";
  const avgAsr = rows.map((r) => parseFloat(r.asrLabel)).filter((v) => !Number.isNaN(v));
  const avgAsrVal = avgAsr.length > 0 ? (avgAsr.reduce((a, b) => a + b, 0) / avgAsr.length).toFixed(3) : "n/a";
  const avgTpr = rows.map((r) => parseFloat(r.tprLabel)).filter((v) => !Number.isNaN(v));
  const avgTprVal = avgTpr.length > 0 ? (avgTpr.reduce((a, b) => a + b, 0) / avgTpr.length).toFixed(3) : "n/a";

  const riskCounts = { high: 0, medium: 0, low: 0 };
  for (const v of aucValues) riskCounts[classifyRisk(v)]++;

  // Split by track
  const reconRows = rows.filter((r) => r.track === "black-box");
  const piaRows = rows.filter((r) => r.track === "gray-box");
  const gsaRows = rows.filter((r) => r.track === "white-box");

  const reconAuc = avgTrackAuc(reconRows);
  const piaAuc = avgTrackAuc(piaRows);
  const gsaAuc = avgTrackAuc(gsaRows);

  // Defense comparison
  const defenseMap = new Map<string, Map<string, { auc: number; asr: number; tpr: number }>>();
  for (const row of rows) {
    if (!defenseMap.has(row.defense)) defenseMap.set(row.defense, new Map());
    const inner = defenseMap.get(row.defense)!;
    if (!inner.has(row.attack)) {
      inner.set(row.attack, { auc: parseFloat(row.aucLabel) || 0, asr: parseFloat(row.asrLabel) || 0, tpr: parseFloat(row.tprLabel) || 0 });
    }
  }

  const defenses = Array.from(defenseMap.keys()).filter((d) => d !== "none" && d !== "None");
  const attacks = Array.from(new Set(rows.map((r) => r.attack)));

  const now = new Date().toLocaleDateString(isZh ? "zh-CN" : "en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  // i18n
  const t = {
    title: isZh ? "DiffAudit 比赛材料" : "DiffAudit Competition Materials",
    subtitle: isZh ? "扩散模型隐私风险审计系统" : "Diffusion Model Privacy Risk Audit System",
    date: isZh ? "生成日期" : "Date",
    platform: "DiffAudit Platform",
    // Summary
    summary: isZh ? "审计摘要" : "Audit Summary",
    totalAudits: isZh ? "审计结果总数" : "Total Audits",
    avgAuc: isZh ? "平均攻击 AUC" : "Avg. Attack AUC",
    avgAsr: isZh ? "平均攻击成功率" : "Avg. Attack Success Rate",
    avgTpr: isZh ? "平均 TPR@1%FPR" : "Avg. TPR@1%FPR",
    contracts: isZh ? "可审计合同" : "Auditable Contracts",
    defended: isZh ? "已评估防御" : "Defenses Evaluated",
    // Attack lines
    attackLines: isZh ? "三条攻击线结果" : "Three Attack Line Results",
    blackBox: isZh ? "黑盒攻击 (Recon)" : "Black-box Attack (Recon)",
    grayBox: isZh ? "灰盒攻击 (PIA)" : "Gray-box Attack (PIA)",
    whiteBox: isZh ? "白盒攻击 (GSA)" : "White-box Attack (GSA)",
    results: isZh ? "条结果" : "results",
    // Defense
    defenseComparison: isZh ? "防御对照实验" : "Defense Comparison",
    defense: isZh ? "防御策略" : "Defense Strategy",
    attack: isZh ? "攻击类型" : "Attack Type",
    auc: "AUC",
    asr: "ASR",
    tpr: "TPR@1%",
    // Innovations
    innovations: isZh ? "创新功能展示" : "Innovation Highlights",
    innovationItems: isZh
      ? [
          "自适应采样：根据中间结果动态调整采样策略，节省计算资源",
          "风险雷达：多维度风险可视化（AUC/ASR/TPR/Coverage/Defense）",
          "工作流引导：根据攻击类型推荐最优配置，自动建议下一步",
          "一键导出：自动生成包含封面、图表、表格的比赛级 PDF 报告",
          "三轨并行：黑盒/灰盒/白盒三条攻击线统一平台管理",
          "双语支持：完整的中文/英文国际化，自然流畅的产品语感",
        ]
      : [
          "Adaptive Sampling: dynamically adjusts sampling strategy based on intermediate results",
          "Risk Radar: multi-dimensional risk visualization (AUC/ASR/TPR/Coverage/Defense)",
          "Workflow Guidance: recommends optimal configurations and suggests next steps",
          "One-click Export: auto-generates competition-ready PDF reports with cover, charts, tables",
          "Three-track Parallel: unified platform for black-box/gray-box/white-box attack lines",
          "Bilingual Support: complete zh-CN/en-US i18n with natural product language",
        ],
    // Risk
    riskOverview: isZh ? "风险分布" : "Risk Distribution",
    high: riskLabel("high", locale),
    medium: riskLabel("medium", locale),
    low: riskLabel("low", locale),
    // Footer
    footer: isZh ? "由 DiffAudit Platform 自动生成 — 扩散模型隐私风险审计系统" : "Auto-generated by DiffAudit Platform — Diffusion Model Privacy Risk Audit System",
  };

  const thStyle = "padding:10px 12px;text-align:left;font-weight:600;font-size:12px;color:#fff;white-space:nowrap;";
  const tdStyle = "padding:8px 12px;font-size:13px;border-bottom:1px solid #e5e7eb;";
  const monoStyle = "font-family:monospace;font-variant-numeric:tabular-nums;";

  function trackTable(trackRows: ReportExportRow[]) {
    return trackRows.map((row) => {
      const auc = parseFloat(row.aucLabel);
      const level = Number.isNaN(auc) ? "low" : classifyRisk(auc);
      const color = level === "high" ? "#dc2626" : level === "medium" ? "#f59e0b" : "#22c55e";
      const label = riskLabel(level, locale);
      return `<tr>
        <td style="${tdStyle}">${row.attack}</td>
        <td style="${tdStyle}">${row.defense}</td>
        <td style="${tdStyle}">${row.model}</td>
        <td style="${tdStyle}${monoStyle}">${row.aucLabel}</td>
        <td style="${tdStyle}${monoStyle}">${row.asrLabel}</td>
        <td style="${tdStyle}${monoStyle}">${row.tprLabel}</td>
        <td style="${tdStyle}"><span style="color:${color};font-weight:600;">${label}</span></td>
      </tr>`;
    }).join("");
  }

  function defenseRows() {
    let html = "";
    for (const def of defenses) {
      const inner = defenseMap.get(def)!;
      for (const atk of attacks) {
        const entry = inner.get(atk);
        if (entry) {
          html += `<tr>
            <td style="${tdStyle}">${def}</td>
            <td style="${tdStyle}">${atk}</td>
            <td style="${tdStyle}${monoStyle}">${entry.auc.toFixed(3)}</td>
            <td style="${tdStyle}${monoStyle}">${entry.asr.toFixed(3)}</td>
            <td style="${tdStyle}${monoStyle}">${entry.tpr.toFixed(3)}</td>
          </tr>`;
        }
      }
    }
    return html;
  }



  return `<!DOCTYPE html>
<html lang="${isZh ? "zh-CN" : "en"}">
<head>
<meta charset="utf-8">
<title>${t.title}</title>
<style>
  body{font-family:-apple-system,"Microsoft YaHei","Noto Sans CJK SC","Segoe UI",sans-serif;max-width:900px;margin:0 auto;padding:40px 32px;color:#1a1a2e;background:#fff}
  /* Cover page */
  .cover{min-height:100vh;display:flex;flex-direction:column;justify-content:center;text-align:center;padding:60px 0;page-break-after:always}
  .cover h1{font-size:36px;font-weight:700;color:#1a1a2e;margin:0 0 12px;letter-spacing:1px}
  .cover .subtitle{font-size:18px;color:#e94560;margin-bottom:32px;font-weight:500}
  .cover .meta{font-size:14px;color:#6b7280;line-height:2}
  .cover .divider{width:60px;height:3px;background:#e94560;margin:24px auto}
  h2{font-size:20px;font-weight:600;margin:32px 0 16px;padding-bottom:8px;border-bottom:2px solid #e94560}
  h3{font-size:16px;font-weight:600;margin:20px 0 12px;color:#1a1a2e}
  .section{margin-bottom:32px;page-break-inside:avoid}
  /* Summary cards */
  .summary-grid{display:grid;grid-template-columns:repeat(5,1fr);gap:12px;margin-bottom:24px}
  .summary-card{padding:16px;background:#f8f9fa;border-radius:8px;text-align:center}
  .summary-card .value{font-size:24px;font-weight:700;color:#1a1a2e}
  .summary-card .label{font-size:11px;color:#6b7280;margin-top:4px}
  /* Risk overview */
  .risk-bar{display:flex;gap:12px;margin-bottom:24px}
  .risk-item{flex:1;padding:14px;border-radius:8px;text-align:center}
  .risk-item .count{font-size:22px;font-weight:700}
  .risk-item .label{font-size:11px;margin-top:4px}
  .risk-high{background:#fef2f2;color:#dc2626}
  .risk-medium{background:#fffbeb;color:#f59e0b}
  .risk-low{background:#f0fdf4;color:#22c55e}
  /* Attack line cards */
  .attack-line{padding:16px;border:1px solid #e5e7eb;border-radius:8px;margin-bottom:12px;border-left:4px solid}
  .attack-line.black-box{border-left-color:#2f6df6}
  .attack-line.gray-box{border-left-color:#b67619}
  .attack-line.white-box{border-left-color:#ff5f46}
  .attack-line .header{display:flex;justify-content:space-between;align-items:center;margin-bottom:8px}
  .attack-line .title{font-weight:600;font-size:14px}
  .attack-line .auc{font-family:monospace;font-size:16px;font-weight:700}
  /* Defense table */
  table{width:100%;border-collapse:collapse;margin:12px 0}
  thead{background:#1a1a2e}
  /* Innovations */
  .innovation-list{list-style:none;padding:0;margin:0}
  .innovation-list li{padding:10px 14px;margin-bottom:6px;background:#f0f9ff;border-left:3px solid #3b82f6;border-radius:0 6px 6px 0;font-size:14px;line-height:1.6}
  /* Footer */
  footer{margin-top:40px;padding-top:16px;border-top:1px solid #e5e7eb;font-size:12px;color:#9ca3af;text-align:center}
</style>
</head>
<body>

<!-- Cover page -->
<div class="cover">
  <h1>${t.title}</h1>
  <div class="subtitle">${t.subtitle}</div>
  <div class="divider"></div>
  <div class="meta">
    ${t.date}: ${now}<br>
    ${t.platform}
  </div>
</div>

<!-- Audit Summary -->
<div class="section">
  <h2>${t.summary}</h2>
  <div class="summary-grid">
    <div class="summary-card">
      <div class="value">${rows.length}</div>
      <div class="label">${t.totalAudits}</div>
    </div>
    <div class="summary-card">
      <div class="value">${avgAuc}</div>
      <div class="label">${t.avgAuc}</div>
    </div>
    <div class="summary-card">
      <div class="value">${avgAsrVal}</div>
      <div class="label">${t.avgAsr}</div>
    </div>
    <div class="summary-card">
      <div class="value">${avgTprVal}</div>
      <div class="label">${t.avgTpr}</div>
    </div>
    <div class="summary-card">
      <div class="value">${catalogSize}</div>
      <div class="label">${t.contracts}</div>
    </div>
  </div>

  <h3>${t.riskOverview}</h3>
  <div class="risk-bar">
    <div class="risk-item risk-high"><div class="count">${riskCounts.high}</div><div class="label">${t.high}</div></div>
    <div class="risk-item risk-medium"><div class="count">${riskCounts.medium}</div><div class="label">${t.medium}</div></div>
    <div class="risk-item risk-low"><div class="count">${riskCounts.low}</div><div class="label">${t.low}</div></div>
  </div>
</div>

<!-- Three Attack Lines -->
<div class="section">
  <h2>${t.attackLines}</h2>

  <div class="attack-line black-box">
    <div class="header">
      <span class="title">${t.blackBox}</span>
      <span class="auc" style="color:#2f6df6">AUC: ${reconAuc} (${reconRows.length} ${t.results})</span>
    </div>
    ${reconRows.length > 0 ? `<table><thead><tr>
      <th style="${thStyle}">Attack</th><th style="${thStyle}">Defense</th><th style="${thStyle}">Model</th>
      <th style="${thStyle}">AUC</th><th style="${thStyle}">ASR</th><th style="${thStyle}">TPR</th><th style="${thStyle}">Risk</th>
    </tr></thead><tbody>${trackTable(reconRows)}</tbody></table>` : `<p style="color:#6b7280;font-size:13px">${isZh ? "暂无黑盒攻击结果" : "No black-box attack results yet"}</p>`}
  </div>

  <div class="attack-line gray-box">
    <div class="header">
      <span class="title">${t.grayBox}</span>
      <span class="auc" style="color:#b67619">AUC: ${piaAuc} (${piaRows.length} ${t.results})</span>
    </div>
    ${piaRows.length > 0 ? `<table><thead><tr>
      <th style="${thStyle}">Attack</th><th style="${thStyle}">Defense</th><th style="${thStyle}">Model</th>
      <th style="${thStyle}">AUC</th><th style="${thStyle}">ASR</th><th style="${thStyle}">TPR</th><th style="${thStyle}">Risk</th>
    </tr></thead><tbody>${trackTable(piaRows)}</tbody></table>` : `<p style="color:#6b7280;font-size:13px">${isZh ? "暂无灰盒攻击结果" : "No gray-box attack results yet"}</p>`}
  </div>

  <div class="attack-line white-box">
    <div class="header">
      <span class="title">${t.whiteBox}</span>
      <span class="auc" style="color:#ff5f46">AUC: ${gsaAuc} (${gsaRows.length} ${t.results})</span>
    </div>
    ${gsaRows.length > 0 ? `<table><thead><tr>
      <th style="${thStyle}">Attack</th><th style="${thStyle}">Defense</th><th style="${thStyle}">Model</th>
      <th style="${thStyle}">AUC</th><th style="${thStyle}">ASR</th><th style="${thStyle}">TPR</th><th style="${thStyle}">Risk</th>
    </tr></thead><tbody>${trackTable(gsaRows)}</tbody></table>` : `<p style="color:#6b7280;font-size:13px">${isZh ? "暂无白盒攻击结果" : "No white-box attack results yet"}</p>`}
  </div>
</div>

<!-- Defense Comparison -->
${defenses.length > 0 ? `<div class="section">
  <h2>${t.defenseComparison}</h2>
  <table>
    <thead><tr>
      <th style="${thStyle}">${t.defense}</th>
      <th style="${thStyle}">${t.attack}</th>
      <th style="${thStyle}">${t.auc}</th>
      <th style="${thStyle}">${t.asr}</th>
      <th style="${thStyle}">${t.tpr}</th>
    </tr></thead>
    <tbody>${defenseRows()}</tbody>
  </table>
</div>` : ""}

<!-- Innovation Highlights -->
<div class="section">
  <h2>${t.innovations}</h2>
  <ul class="innovation-list">
    ${t.innovationItems.map((item) => `<li>${item}</li>`).join("")}
  </ul>
</div>

<footer>${t.footer}</footer>
</body>
</html>`;
}

function avgTrackAuc(trackRows: ReportExportRow[]): string {
  const aucs = trackRows.map((r) => parseFloat(r.aucLabel)).filter((v) => !Number.isNaN(v));
  return aucs.length > 0 ? (aucs.reduce((a, b) => a + b, 0) / aucs.length).toFixed(3) : "n/a";
}
