/**
 * Snapshot data for Demo Mode.
 * Used when the Runtime server is unavailable.
 */
import type { CatalogEntryPayload } from "@/lib/catalog";
import type { AttackDefenseRowPayload } from "@/lib/attack-defense-table";

/** Demo catalog entries — pre-seeded with realistic attack model data */
export const DEMO_CATALOG_ENTRIES: CatalogEntryPayload[] = [
  // Black-box track
  {
    contract_key: "recon_artifact_mainline",
    track: "black-box",
    attack_family: "recon",
    target_key: "stable-diffusion-v1-4",
    label: "Recon + SD v1.4",
    backend: "runtime-go",
    scheduler: "local",
    availability: "ready",
    evidence_level: "mainline",
    system_gap: "Membership inference via loss deviation.",
  },
  {
    contract_key: "recon_artifact_pixel",
    track: "black-box",
    attack_family: "recon",
    target_key: "pixel-art-v2",
    label: "Recon + PixelArt v2",
    backend: "runtime-go",
    scheduler: "local",
    availability: "ready",
    evidence_level: "catalog",
    system_gap: "Attribute-level membership inference.",
  },
  // Gray-box track
  {
    contract_key: "pia_runtime_mainline",
    track: "gray-box",
    attack_family: "PIA",
    target_key: "stable-diffusion-v1-4",
    label: "PIA + SD v1.4",
    backend: "runtime-go",
    scheduler: "local",
    availability: "ready",
    evidence_level: "mainline",
    system_gap: "Gradient leakage through posterior deviation.",
  },
  {
    contract_key: "pia_runtime_pixel",
    track: "gray-box",
    attack_family: "PIA",
    target_key: "pixel-art-v2",
    label: "PIA + PixelArt v2",
    backend: "runtime-go",
    scheduler: "local",
    availability: "partial",
    evidence_level: "catalog",
    system_gap: "Targeted attribute leakage.",
  },
  // White-box track
  {
    contract_key: "gsa_runtime_mainline",
    track: "white-box",
    attack_family: "GSA",
    target_key: "stable-diffusion-v1-4",
    label: "GSA + SD v1.4",
    backend: "runtime-go",
    scheduler: "local",
    availability: "ready",
    evidence_level: "mainline",
    system_gap: "Saliency-guided gradient extraction.",
  },
  {
    contract_key: "gsa_runtime_pixel",
    track: "white-box",
    attack_family: "GSA",
    target_key: "pixel-art-v2",
    label: "GSA + PixelArt v2",
    backend: "runtime-go",
    scheduler: "local",
    availability: "ready",
    evidence_level: "catalog",
    system_gap: "Cross-model gradient transfer.",
  },
];

/** Demo attack-defense table — snapshot of known results */
export const DEMO_ATTACK_DEFENSE_ROWS: AttackDefenseRowPayload[] = [
  // Black-box: Recon on SD v1.4
  {
    track: "black-box",
    attack: "recon",
    defense: "none",
    model: "stable-diffusion-v1-4",
    auc: 0.849,
    asr: 0.51,
    tpr_at_1pct_fpr: 1.0,
    evidence_level: "admitted",
    note: "Black-box membership inference via loss deviation. High AUC indicates significant leakage.",
  },
  {
    track: "black-box",
    attack: "recon",
    defense: "SMP-LoRA",
    model: "stable-diffusion-v1-4",
    auc: 0.712,
    asr: 0.38,
    tpr_at_1pct_fpr: 0.82,
    quality_cost: "PSNR drop: 0.3dB",
    evidence_level: "exploratory",
    note: "SMP-LoRA reduces leakage but with minor quality trade-off.",
  },
  // Gray-box: PIA on SD v1.4
  {
    track: "gray-box",
    attack: "PIA",
    defense: "none",
    model: "stable-diffusion-v1-4",
    auc: 0.828,
    asr: 0.768,
    tpr_at_1pct_fpr: 0.95,
    evidence_level: "admitted",
    note: "Gray-box posterior deviation attack. High ASR shows gradient leakage is exploitable.",
  },
  {
    track: "gray-box",
    attack: "PIA",
    defense: "stochastic-dropout",
    model: "stable-diffusion-v1-4",
    auc: 0.791,
    asr: 0.62,
    tpr_at_1pct_fpr: 0.88,
    quality_cost: "Inference overhead: +12%",
    evidence_level: "admitted",
    note: "Stochastic dropout at all steps reduces ASR by ~15pp with moderate overhead.",
  },
  {
    track: "gray-box",
    attack: "PIA",
    defense: "SMP-LoRA",
    model: "stable-diffusion-v1-4",
    auc: 0.756,
    asr: 0.51,
    tpr_at_1pct_fpr: 0.79,
    quality_cost: "PSNR drop: 0.5dB",
    evidence_level: "exploratory",
    note: "SMP-LoRA shows stronger mitigation under gray-box attack.",
  },
  // White-box: GSA on SD v1.4
  {
    track: "white-box",
    attack: "GSA",
    defense: "none",
    model: "stable-diffusion-v1-4",
    auc: 0.489,
    asr: 0.499,
    tpr_at_1pct_fpr: 0.12,
    evidence_level: "admitted",
    note: "GSA + W-1 defense achieves near-random AUC, demonstrating effective white-box mitigation.",
  },
  {
    track: "white-box",
    attack: "GSA",
    defense: "W-1",
    model: "stable-diffusion-v1-4",
    auc: 0.489,
    asr: 0.499,
    tpr_at_1pct_fpr: 0.12,
    quality_cost: "Minimal perceptual impact",
    evidence_level: "admitted",
    note: "W-1 gradient masking effectively neutralizes saliency-guided extraction.",
  },
  // Black-box on PixelArt
  {
    track: "black-box",
    attack: "recon",
    defense: "none",
    model: "pixel-art-v2",
    auc: 0.791,
    asr: 0.44,
    tpr_at_1pct_fpr: 0.91,
    evidence_level: "catalog",
    note: "Lower AUC on PixelArt suggests stronger baseline privacy.",
  },
  // Gray-box on PixelArt
  {
    track: "gray-box",
    attack: "PIA",
    defense: "none",
    model: "pixel-art-v2",
    auc: 0.773,
    asr: 0.69,
    tpr_at_1pct_fpr: 0.89,
    evidence_level: "catalog",
    note: "Gradient leakage present but lower magnitude than SD v1.4.",
  },
  // White-box on PixelArt
  {
    track: "white-box",
    attack: "GSA",
    defense: "W-1",
    model: "pixel-art-v2",
    auc: 0.512,
    asr: 0.501,
    tpr_at_1pct_fpr: 0.15,
    evidence_level: "catalog",
    note: "W-1 effective on PixelArt as well.",
  },
];
